config/routes.rb
resources :approvable_time_entries, only: [:index] do
  get 'report', on: :collection
  patch 'bulk_approve', on: :collection
end

resources :projects do
  resources :approvable_time_entries, only: [:index] do
    get 'report', on: :collection
    patch 'bulk_approve', on: :collection
  end
end

app/models/approvable_time_entry_query.rb
class ApprovableTimeEntryQuery < TimeEntryQuery

  self.available_columns << QueryColumn.new(:approved, sortable: "#{self.queried_class.table_name}.approved")
  self.available_columns << QueryColumn.new(:approved_by)
  self.available_columns << QueryColumn.new(:created_on)
  self.available_columns << QueryColumn.new(:approved_comment)

  def default_columns_names
    @default_columns_names ||= super.push(:approved, :approved_by, :created_on, :approved_comment)
  end

  def initialize_available_filters
    super
    # add filter field "Approved by" to selectbox
    users = User.all.to_a.reject! {|u| !u.allowed_to?(:approvable_time_entries, nil, global: true)}
    users_values = []
    users_values << ["<< #{l(:label_me)} >>", "me"] if User.current.logged?
    users_values += users.collect{|s| [s.name, s.id.to_s] }
    add_available_filter("approved_by_user_id",
      :type => :list_optional, :values => users_values
    ) unless users_values.empty?
  end

  def build_from_params(params)
    super
    # replace placeholder "me" with current user ID
    value = values_for('approved_by_user_id')
    if value
      if value.delete("me")
        value.push(User.current.id.to_s)
      end
    end
    self
  end

end

app/controllers/approvable_time_entries_controller.rb
class ApprovableTimeEntriesController < ApplicationController

  before_filter :find_time_entries, :only => [:bulk_approve]
  before_filter :authorize, :only => [:bulk_approve]

  before_filter :find_optional_project, :only => [:index, :report]
  before_filter :authorize_global, :only => [:index, :report]

  rescue_from Query::StatementInvalid, :with => :query_statement_invalid

  helper :sort
  include SortHelper
  helper :issues
  include TimelogHelper
  helper :timelog
  include TimeApprovalHelper
  helper :time_approval
  helper :custom_fields
  include CustomFieldsHelper
  helper :queries
  include QueriesHelper
  helper :routes

  def index
    set_params_for_default_filters

    @query = ApprovableTimeEntryQuery.build_from_params(params, :project => @project, :name => '_')

    sort_init(@query.sort_criteria.empty? ? [['spent_on', 'desc']] : @query.sort_criteria)
    sort_update(@query.sortable_columns)
    scope = time_entry_scope(:order => sort_clause).
      includes(:project, :user, :issue).
      preload(:issue => [:project, :tracker, :status, :assigned_to, :priority])

    if !can_user_approve_own_entries?
      scope = scope.where.not(user: User.current)
    end

    respond_to do |format|
      format.html {
        @entry_count = scope.count
        @entry_pages = Paginator.new @entry_count, per_page_option, params['page']
        @entries = scope.offset(@entry_pages.offset).limit(@entry_pages.per_page).to_a
        @total_hours = scope.sum(:hours).to_f

        render :layout => !request.xhr?
      }
      format.api  {
        @entry_count = scope.count
        @offset, @limit = api_offset_and_limit
        @entries = scope.offset(@offset).limit(@limit).preload(:custom_values => :custom_field).to_a
      }
      format.atom {
        entries = scope.limit(Setting.feeds_limit.to_i).reorder("#{TimeEntry.table_name}.created_on DESC").to_a
        render_feed(entries, :title => l(:label_spent_time))
      }
      format.csv {
        # Export all entries
        @entries = scope.to_a
        send_data(query_to_csv(@entries, @query, params), :type => 'text/csv; header=present', :filename => 'timelog.csv')
      }
    end
  end

  def report
    @query = ApprovableTimeEntryQuery.build_from_params(params, :project => @project, :name => '_')
    scope = time_entry_scope

    @report = TimeApproval::Helpers::TimeReport.new(@project, @issue, params[:criteria], params[:columns], scope)

    respond_to do |format|
      format.html { render :layout => !request.xhr? }
      format.csv  { send_data(report_to_csv(@report), :type => 'text/csv; header=present', :filename => 'timelog.csv') }
    end
  end

  def bulk_approve
    if params[:reject]
      message_sym = :notice_successful_reject
    else
      message_sym = :notice_successful_approve
    end

    unsaved_time_entry_ids = []
    @time_entries.each do |time_entry|
      time_entry.reload

      if params[:reject]
        time_entry.approved = false
      else
        time_entry.approved = true
      end

      time_entry.approved_by = User.current
      time_entry.approved_at = DateTime.now
      time_entry.approved_comment = params[:approved_comment][time_entry.id.to_s]

      unless time_entry.save
        logger.info "time entry could not be saved: #{time_entry.errors.full_messages}" if logger && logger.info?
        # Keep unsaved time_entry ids to display them in flash error
        unsaved_time_entry_ids << time_entry.id
      end
    end
    set_flash_from_bulk_time_entry_action(message_sym, @time_entries, unsaved_time_entry_ids)
    redirect_back_or_default approvable_time_entries_path
  end


private
  def set_params_for_default_filters
    params[:f] = ['spent_on', 'approved'] unless params[:f]

    spent_on_setting = Setting.plugin_time_approval['spent_on_filter_value']
    params[:op] = { spent_on: spent_on_setting, approved: '!*' } unless params[:op]
  end

  # Returns the TimeEntry scope for index and report actions
  def time_entry_scope(options={})
    scope = @query.results_scope(options)
    if @issue
      scope = scope.on_issue(@issue)
    end
    scope
  end

  def set_flash_from_bulk_time_entry_action(message_sym, time_entries, unsaved_time_entry_ids)
    if unsaved_time_entry_ids.empty?
      flash[:notice] = l(message_sym) unless time_entries.empty?
    else
      flash[:error] = l(:notice_failed_to_save_time_entries,
                        :count => unsaved_time_entry_ids.size,
                        :total => time_entries.size,
                        :ids => '#' + unsaved_time_entry_ids.join(', #'))
    end
  end

  def find_optional_project
    if params[:issue_id].present?
      @issue = Issue.find(params[:issue_id])
      @project = @issue.project
    elsif params[:project_id].present?
      @project = Project.find(params[:project_id])
    end
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_time_entries
    @time_entries = TimeEntry.where(:id => params[:id] || params[:ids]).
      preload(:project => :time_entry_activities).
      preload(:user).to_a

    raise ActiveRecord::RecordNotFound if @time_entries.empty?
    raise Unauthorized unless @time_entries.all? {|t| approvable_by_current_user?(t)}
    @projects = @time_entries.collect(&:project).compact.uniq
    @project = @projects.first if @projects.size == 1
  rescue ActiveRecord::RecordNotFound
    redirect_back_or_default approvable_time_entries_path
  end

end

app/helpers/time_approval_helper.rb
module TimeApprovalHelper
  include ApplicationHelper

  def can_user_approve_own_entries?
    User.current.admin? || Setting.plugin_time_approval['approve_own_time_entries']
  end

  def approvable_by_current_user?(time_entry)
    return true if User.current.admin?

    is_project_member = User.current.membership(time_entry.project)

    if Setting.plugin_time_approval['approve_own_time_entries']
      is_project_member
    else
      is_project_member && time_entry.user != User.current
    end
  end

  def format_approved_field(time_entry)
    approved = time_entry['approved']
    return '-' if approved.nil?

    value = approved ? l(:approved) : l(:rejected)

    approved_at_str = ' (' << format_object(time_entry['approved_at'].to_date) << ')'

    output = format_object(value) << approved_at_str
    output = '-' unless output.present?

    output
  end

  def format_approved_comment(time_entry, editable)
    id      = time_entry['id']
    comment = time_entry['approved_comment']

    if editable
      output = content_tag('input', nil, name: "approved_comment[#{id}]", value: comment, type: 'text')
    else
      output = format_object(comment)
    end

    output
  end
end

app/views/approvable_time_entries/_date_range.html.erb
<div id="query_form_with_buttons" class="hide-when-print">
<div id="query_form_content">
  <fieldset id="filters" class="collapsible <%= @query.new_record? ? "" : "collapsed" %>">
    <legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
    <div style="<%= @query.new_record? ? "" : "display: none;" %>">
      <%= render :partial => 'queries/filters', :locals => {:query => @query} %>
    </div>
  </fieldset>
  <fieldset id="options" class="collapsible collapsed">
    <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
    <div style="display: none;">
      <table>
        <tr>
          <td class="field"><%= l(:field_column_names) %></td>
          <td><%= render_query_columns_selection(@query) %></td>
        </tr>
      </table>
    </div>
  </fieldset>
</div>

<p class="buttons">
  <%= link_to_function l(:button_apply), '$("#query_form").submit()', :class => 'icon icon-checked' %>
  <%= link_to l(:button_clear), {:project_id => @project, :issue_id => @issue}, :class => 'icon icon-reload'  %>
</p>
</div>

<div class="tabs hide-when-print">
<% query_params = params.slice(:f, :op, :v, :sort) %>
<ul>
    <li><%= link_to(l(:label_details), _approvable_time_entries_path(@project, @issue, query_params),
                                       :class => (action_name == 'index' ? 'selected' : nil)) %></li>
    <li><%= link_to(l(:label_report), _report_approvable_time_entries_path(@project, @issue, query_params),
                                       :class => (action_name == 'report' ? 'selected' : nil)) %></li>
</ul>
</div>

app/views/approvable_time_entries/_list.html.erb
<%= form_tag({action: :bulk_approve}, method: :patch) do -%>
<%
  url_params = params.dup
  url_params.delete(:project_id) unless url_params[:project].present?
%>
<%= hidden_field_tag 'back_url', url_for(url_params) %>
<div class="autoscroll">

<table class="list time-entries">
  <thead>
    <tr>
      <th class="checkbox hide-when-print">
        <%= check_box_tag 'check_all', '', false, :class => 'toggle-selection',
          :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
      </th>
      <% @query.inline_columns.each do |column| %>
        <%= column_header(column) %>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% entries.each do |entry| -%>
    <tr class="time-entry <%= cycle("odd", "even") %> hascontextmenu">
      <% disabled = true if !approvable_by_current_user?(entry) || entry.approved? %>
      <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", entry.id, false, id: nil, disabled: disabled) %></td>
      <% @query.inline_columns.each do |column| %>
      <%= content_tag('td', column_content(column, entry), :class => column.css_classes) %>
      <% end %>
    </tr>
  <% end -%>
  </tbody>
  </table>

  <p>
    <%= submit_tag l(:button_approve), :class => 'button-small', :name => 'approve' %>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <%= submit_tag l(:button_reject), :class => 'button-small', :name => 'reject' %>
  </p>

</div>
<% end -%>

<%= javascript_tag do %>
function toggleRowsSelection(el) {
  var checked = $(this).prop('checked');
  var boxes = $(this).parents('table').find('input[name=ids\\[\\]]');
  boxes.prop('checked', checked).parents('tr').toggleClass('context-menu-selection', checked);
}

$(document).ready(function(){
  $('input[type=checkbox].toggle-selection').on('change', toggleRowsSelection);
});
<% end %>

app/views/approvable_time_entries/_report_criteria.html.erb
<% @report.hours.collect {|h| h[criterias[level]].to_s}.uniq.each do |value| %>
<% hours_for_value = select_hours(hours, criterias[level], value) -%>
<% next if hours_for_value.empty? -%>
<tr class="<%= cycle('odd', 'even') %> <%= criterias.length > level+1 ? 'subtotal' : 'last-level' %>">
<%= ("<td></td>" * level).html_safe %>
<td class="name"><%= format_criteria_value(@report.available_criteria[criterias[level]], value) %></td>
<%= ("<td></td>" * (criterias.length - level - 1)).html_safe -%>
  <% total = 0 -%>
  <% @report.periods.each do |period| -%>
    <% sum = sum_hours(select_hours(hours_for_value, @report.columns, period.to_s)); total += sum -%>
<!--    <td class="hours"><%= html_hours("%.2f" % sum) if sum > 0 %></td> -->
  <% end -%>
  <td class="hours"><%= html_hours("%.2f" % total) if total > 0 %></td>
</tr>

<tr>
<%= ("<td></td>" * level).html_safe %>
<td class="name">
<% if level == criterias.length - 1 %>
  <table class="report-time-entry">
    <% hours_for_value.each do |te| %>
      <% time_entry = TimeEntry.find(te['id']) %>
      <% disabled = true if !approvable_by_current_user?(time_entry) || time_entry.approved? %>
      <tr class="time-entry <%= cycle("odd", "even") %>">
        <td><%= check_box_tag("ids[]", te['id'], false, id: nil, disabled: disabled) %></td>
        <td><%= format_object(te['spent_on']) %></td>
        <td><%= format_object(te['comments']) %></td>
        <td><%= format_object(te['hours']) %></td>
        <td><%= format_approved_field(te) %></td>
        <td><%= format_approved_comment(te, !disabled) %></td>
      </tr>
    <% end %>
  </table>
<% end %>
</td>
<%= ("<td></td>" * (criterias.length - level - 1)).html_safe -%>
<td class="hours"></td>
</tr>

<% if criterias.length > level+1 -%>
  <%= render(:partial => 'report_criteria', :locals => {:criterias => criterias, :hours => hours_for_value, :level => (level + 1)}) %>
<% end -%>

<% end %>

app/views/approvable_time_entries/index.html.erb
<%= render_timelog_breadcrumb %>

<h2><%= l(:label_approvable_entry_plural) %></h2>

<%= form_tag({}, :method => :get, :id => 'query_form') do %>
<%= hidden_field_tag 'project_id', params[:project_id] %>
<%= render :partial => 'date_range' %>
<% end %>

<div class="total-hours">
<p><%= l(:label_total_time) %>: <%= html_hours(l_hours(@total_hours)) %></p>
</div>

<% unless @entries.empty? %>
<%= render :partial => 'list', :locals => { :entries => @entries }%>
<span class="pagination"><%= pagination_links_full @entry_pages, @entry_count %></span>
<% end %>

app/views/approvable_time_entries/report.html.erb
<div class="contextual">
<%= link_to l(:button_log_time), 
            _new_time_entry_path(@project, @issue),
            :class => 'icon icon-time-add' if User.current.allowed_to?(:log_time, @project, :global => true) %>
</div>

<%= render_timelog_breadcrumb %>

<h2><%= l(:label_approvable_entry_plural) %></h2>

<%= form_tag(params.slice(:project_id, :issue_id), :method => :get, :id => 'query_form') do %>
  <% @report.criteria.each do |criterion| %>
    <%= hidden_field_tag 'criteria[]', criterion, :id => nil %>
  <% end %>
  <%= render :partial => 'date_range' %>

  <p>


  <label for='criterias'><%= l(:button_add) %></label>: <%= select_tag('criteria[]', options_for_select([[]] + (@report.available_criteria.keys - @report.criteria).collect{|k| [l_or_humanize(@report.available_criteria[k][:label]), k]}),
                                                          :onchange => "this.form.submit();",
                                                          :style => 'width: 200px',
                                                          :disabled => (@report.criteria.length >= 3),
                                                          :id => "criterias") %>
     <%= link_to l(:button_clear), {:params => request.query_parameters.merge(:criteria => nil)}, :class => 'icon icon-reload' %></p>
<% end %>

<% unless @report.criteria.empty? %>
<div class="total-hours">
<p><%= l(:label_total_time) %>: <%= html_hours(l_hours(@report.total_hours)) %></p>
</div>

<% unless @report.hours.empty? %>
<%= form_tag({action: :bulk_approve}, method: :patch) do -%>
<%
  url_params = params.dup
  url_params.delete(:project_id) unless url_params[:project].present?
%>
<%= hidden_field_tag 'back_url', url_for(url_params) %>

<div class="autoscroll">
<table class="list" id="time-report">
<thead>
<tr>
<% @report.criteria.each do |criteria| %>
  <th><%= l_or_humanize(@report.available_criteria[criteria][:label]) %></th>
<% end %>
<% columns_width = (40 / (@report.periods.length+1)).to_i %>
<% @report.periods.each do |period| %>
<!--  <th class="period" style="width:<%= columns_width %>%;"><%= period %></th> -->
<% end %>
  <th class="total" style="width:<%= columns_width %>%;"><%= l(:label_total_time) %></th>
</tr>
</thead>
<tbody>
<%= render :partial => 'report_criteria', :locals => {:criterias => @report.criteria, :hours => @report.hours, :level => 0} %>
  <tr class="total">
  <td><%= l(:label_total_time) %></td>
  <%= ('<td></td>' * (@report.criteria.size - 1)).html_safe %>
  <% total = 0 -%>
  <% @report.periods.each do |period| -%>
    <% sum = sum_hours(select_hours(@report.hours, @report.columns, period.to_s)); total += sum -%>
<!--    <td class="hours"><%= html_hours("%.2f" % sum) if sum > 0 %></td> -->
  <% end -%>
  <td class="hours"><%= html_hours("%.2f" % total) if total > 0 %></td>
  </tr>
</tbody>
</table>
</div>

<p>
  <%= submit_tag l(:button_approve), :class => 'button-small', :name => 'approve' %>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= submit_tag l(:button_reject), :class => 'button-small', :name => 'reject' %>
</p>

<% end %>

<% other_formats_links do |f| %>
  <%= f.link_to 'CSV', :url => params %>
<% end %>
<% end %>
<% end %>

<% html_title l(:label_spent_time), l(:label_report) %>

<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'main', plugin: 'time_approval' %>
<% end %>

app/views/settings/_time_approval_settings.erb
<%
  labels = TimeEntryQuery.operators_labels
  collection = {}
  ["t", "ld", "w", "lw", "l2w", "m", "lm", "y"].each do |cond|
    collection[labels[cond]] = cond
  end
%>
<p>
  <%= content_tag(:label, l(:settings_spent_on_filter_value_label)) %>
  <%= select_tag 'settings[spent_on_filter_value]', options_for_select(collection, settings['spent_on_filter_value']) %>
</p>

<p>
  <%= content_tag(:label, l(:settings_approve_own_time_entries)) %>
  <%= check_box_tag 'settings[approve_own_time_entries]', true, settings['approve_own_time_entries'] %>
</p>

app/views/timelog/_list.html.erb
<%= form_tag({}) do -%>
<%= hidden_field_tag 'back_url', url_for(params) %>
<div class="autoscroll">
<table class="list time-entries">
<thead>
  <tr>
    <th class="checkbox hide-when-print">
      <%= check_box_tag 'check_all', '', false, :class => 'toggle-selection',
        :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
    </th>
    <% @query.inline_columns.each do |column| %>
      <%= column_header(column) %>
    <% end %>
    <th></th>
  </tr>
</thead>
<tbody>
<% entries.each do |entry| -%>
  <tr class="time-entry <%= cycle("odd", "even") %> hascontextmenu">
    <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", entry.id, false, :id => nil) %></td>
    <% @query.inline_columns.each do |column| %>
    <%= content_tag('td', column_content(column, entry), :class => column.css_classes) %>
    <% end %>
    <td class="buttons">
    <% if entry.editable_by?(User.current) && !entry.approved? -%>
        <%= link_to l(:button_edit), edit_time_entry_path(entry),
                    :title => l(:button_edit),
                    :class => 'icon-only icon-edit' %>
        <%= link_to l(:button_delete), time_entry_path(entry),
                    :data => {:confirm => l(:text_are_you_sure)},
                    :method => :delete,
                    :title => l(:button_delete),
                    :class => 'icon-only icon-del' %>
    <% end -%>
    </td>
  </tr>
<% end -%>
</tbody>
</table>
</div>
<% end -%>

<%= context_menu time_entries_context_menu_path %>